name: Data Quality Pipeline

on:
  push:
    branches: [ main ] # Se activa al subir código

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Automated Quality Audit
        run: |
          python -m pytest tests/test_slas.py --html=report_ci.html --self-contained-html